### ISSUE TITLE
CovJSON button in the OPeNDAP GUI

### ISSUE THREAD

**Issue by hemphilc** [RiverHendriksen/bes#32]
CovJSON button in the OPeNDAP GUI that you can click on to send request to back-end, and include CovJSON specs, and info to help evangelize CovJSON module.

**Comment by hemphilc** [comment]
I'll start looking into what it will take to do this.

**Comment by RiverHendriksen** [comment]
This is already on the olfs and was going to be put off

**Comment by lewismc** [comment]
@RiverHendriksen can you point me to the code implementation in the branch? Thanks

**Comment by RiverHendriksen** [comment]
@lewismc we discussed with Nathan that this feature is not going to be implemented since he will just set up the olfs section. If he only implements a url line call on the olfs then we can look at the button implementation, but we cannot implement it until a url call is made to the olfs since it will use many of the same subcalls.

**Comment by rrimer07** [comment]
He was talking about the issue itself being on the olfs https://github.com/RiverHendriksen/olfs/issues/3
But it is being put off for now along with other olfs work until the the module in the bes is working

**Comment by RiverHendriksen** [comment]
My bad!

**Comment by lewismc** [comment]
np thanks
